version: "2.4"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  volumes:
  - "C:/Users/Youssef/Desktop/Docker/data:/var/lib/mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=entreprise      
   - MYSQL_USER=root
   - MYSQL_PASSWORD=root
  ports:
   - "3302:3306"
  stdin_open: true
  tty: true 
   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - 1235:80
  depends_on:
   - mysqldb
  environment:
   - PMA_HOST=mysqldb
   - PMA_USER=root
   - PMA_PASSWORD=root
   
 Timesheet-entreprise:
  build: .
  image: entreprise
  ports:
   - 8082:8082
  depends_on:
   - mysqldb
  environment:
  
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3302/entreprise?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
        "spring.datasource.username" : "root"
        "spring.datasource.password" : "root"
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
        "spring.jpa.hibernate.ddl-auto" : "update"
      
     
