version: "2.4"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  volumes:
  - "C:/Users/Youssef/Desktop/Docker/data:/var/lib/mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=entreprise      
   - MYSQL_USER=youssef
   - MYSQL_PASSWORD=youssef
  ports:
   - "3302:3306"
 
   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - 1235:80
  depends_on:
   - mysqldb
  environment:
   - PMA_HOST=mysqldb
   - PMA_USER=youssef
   - PMA_PASSWORD=youssef
   
 Timesheet-entreprise:
  build: \
  image: entreprise
  ports:
   - 8082:8082
  depends_on:
   - mysqldb
  environment:
    SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3302/entreprise?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "youssef",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
     }'   
  stdin_open: true
  tty: true
  
      
     
