version: "2.4"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  volumes:
  - "C:/Users/Youssef/Desktop/Docker/data:/var/lib/mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=entreprise      
   - MYSQL_USER=youssef
   - MYSQL_PASSWORD=youssef
  ports:
   - "3302:3306"
 
   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - 1235:80
  depends_on:
   - mysqldb
  environment:
   - PMA_HOST=mysqldb
   - PMA_USER=youssef
   - PMA_PASSWORD=youssef
   
 Timesheet-entreprise:
  build: \
   image: springboot-docker-container
  ports:
   - 8082:8082
  depends_on:
   - mysqldb
 environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/timeSheetDevOps?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "youssef"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      
  stdin_open: true
  tty: true
