version: "2.4"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
 
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=employe      
   - MYSQL_USER=devops
   - MYSQL_PASSWORD=devops
  ports:
   - "3306:3306"
 

 devopsApp:
  build:
      context: "./"
      dockerfile: "Dockerfile"
  image: devops
  ports:
   - 8088:8088
  depends_on:
   - mysqldb
  environment:
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/employe?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "devops",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
   
      
  stdin_open: true
  tty: true
